version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - /usr/local/bin/aws s3 sync . s3://th-dest1 --exclude "*" --include "*.yml"
  post_build:
    commands:
      - echo Build completed on `date`
