AWSTemplateFormatVersion: "2010-09-09"
Description: "CodeBuild and CodePipeline for template sync"

Parameters:
  OAuth:
    Type: String
    Description: The OAuth token to use for the repo

Resources:
  CopyTemplates:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: 
        testlibnd-ESU-Template-Sync
      Description:
        "Template Sync for ESU repository"
      ServiceRole:
        !ImportValue testlibnd-ESU-CF
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/ubuntu-base:14.04
      Source:
        Location: https://github.com/hanstra/th-repo2
        Type: GITHUB
      Artifacts:
        Name: codebuild-output
        Type: S3
        Location: th-source1
      TimeoutInMinutes: 10

#        !Join [' ',[!ImportValue account-alias, ESU-Template-Sync]]

  AppPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: 
        testlibnd-ESU-Template-Sync
      RoleArn:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/AWS-CodePipeline-Service
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: GithubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: hanstra
                Repo: th-repo2
                Branch: master
                OAuthToken: !Ref OAuth
              OutputArtifacts:
                - Name: SourceOutput
        -
          Name: Build
          Actions:
            -
              Name: CopyFiles
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName:
                  Ref: CopyTemplates
      ArtifactStore:
        Type: S3
        Location: th-dest1
